### ISSUE TITLE
ModuleNotFoundError: No module named 'future'

### ISSUE THREAD

**Issue by yuhe-Ray** [keiohta/tf2rl#160]
when i run:

import gym
from tf2rl.algos.ddpg import DDPG
from tf2rl.experiments.trainer import Trainer

parser = Trainer.get_argument()
parser = DDPG.get_argument(parser)
args = parser.parse_args()

env = gym.make("Pendulum-v1")
test_env = gym.make("Pendulum-v1")
policy = DDPG(
    state_shape=env.observation_space.shape,
    action_dim=env.action_space.high.size,
    gpu=-1,  # Run on CPU. If you want to run on GPU, specify GPU number
    memory_capacity=10000,
    max_action=env.action_space.high[0],
    batch_size=32,
    n_warmup=500)
trainer = Trainer(policy, env, args, test_env=test_env)
trainer()
 
the pycharm shows as follow:

  import imp
Traceback (most recent call last):
  File "/Users/heyu/Documents/PycharmProjects/My_7th/train_ddpg.py", line 4, in <module>
    from tf2rl.experiments.trainer import Trainer
  File "/Users/heyu/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/tf2rl/experiments/trainer.py", line 12, in <module>
    from tf2rl.misc.prepare_output_dir import prepare_output_dir
  File "/Users/heyu/opt/anaconda3/envs/tensorflow/lib/python3.8/site-packages/tf2rl/misc/prepare_output_dir.py", line 29, in <module>
    from future import standard_library
ModuleNotFoundError: No module named 'future'

how to solve this issue?

**Comment by yuhe-Ray** [comment]
pip install future
