### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'version'

### ISSUE THREAD

**Issue by marralesfios** [keiohta/tf2rl#163]
Error while installing
```
Collecting tf2rl
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/57/29/79e19932f384bfacbe61d394a112c426d1ebabe7a8d747c53d05ef74ac82/tf2rl-1.1.5.tar.gz (65 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Progr\AppData\Local\Temp\pip-install-rrtgywrc\tf2rl_1791f1cb140d4c828e78af8fb062c883\setup.py", line 17, in <module>
          tf_version = tf.version.VERSION.rsplit('.', 1)[0]
      AttributeError: module 'tensorflow' has no attribute 'version'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by marralesfios** [comment]
Oops, turns out my tensorflow installation is broken
