### ISSUE TITLE
Running DQN instance error

### ISSUE THREAD

**Issue by lichongcoco** [keiohta/tf2rl#79]
DQN settings:(use simultaneously)
parser.set_defaults(enable_double_dqn=True)
parser.set_defaults(enable_categorical_dqn=True)

env = gym.make("CartPole-v0")

Error:
ValueError: Shape must be rank 2 but is rank 3 for 'concat_1' (op: 'ConcatV2') with input shapes: [32,1], [32,1,51], [].

**Comment by keiohta** [comment]
Hi @lichongcoco, thank you for trying. That works on my environment. The log is:
```bash
$ cat examples/run_dqn.py 
import gym

from tf2rl.algos.dqn import DQN
from tf2rl.experiments.trainer import Trainer


if __name__ == '__main__':
    parser = Trainer.get_argument()
    parser = DQN.get_argument(parser)
    parser.set_defaults(test_interval=2000)
    parser.set_defaults(max_steps=100000)
    parser.set_defaults(gpu=-1)
    parser.set_defaults(n_warmup=500)
    parser.set_defaults(batch_size=32)
    parser.set_defaults(memory_capacity=int(1e4))
    parser.set_defaults(enable_double_dqn=True)
    parser.set_defaults(enable_categorical_dqn=True)
    args = parser.parse_args()

    env = gym.make("CartPole-v0")
    test_env = gym.make("CartPole-v0")
    policy = DQN(
        enable_double_dqn=args.enable_double_dqn,
        enable_dueling_dqn=args.enable_dueling_dqn,
        enable_noisy_dqn=args.enable_noisy_dqn,
        enable_categorical_dqn=args.enable_categorical_dqn,
        state_shape=env.observation_space.shape,
        action_dim=env.action_space.n,
        target_replace_interval=300,
        discount=0.99,
        gpu=args.gpu,
        memory_capacity=args.memory_capacity,
        batch_size=args.batch_size,
        n_warmup=args.n_warmup)
    trainer = Trainer(policy, env, args, test_env=test_env)
    trainer()

$ python examples/run_dqn.py 
...
14:43:04.217 [INFO] (trainer.py:105) Total Epi:   299 Steps:    9830 Episode Steps:   200 Return:  200.0000 FPS: 546.44
14:43:05.106 [INFO] (trainer.py:133) Evaluation Total Steps:   10000 Average Reward  200.0000 over  5 episodes
14:43:05.180 [INFO] (trainer.py:105) Total Epi:   300 Steps:   10030 Episode Steps:   200 Return:  200.0000 FPS: 207.64
14:43:05.559 [INFO] (trainer.py:105) Total Epi:   301 Steps:   10230 Episode Steps:   200 Return:  200.0000 FPS: 528.60
14:43:05.933 [INFO] (trainer.py:105) Total Epi:   302 Steps:   10430 Episode Steps:   200 Return:  200.0000 FPS: 535.61
14:43:06.302 [INFO] (trainer.py:105) Total Epi:   303 Steps:   10630 Episode Steps:   200 Return:  200.0000 FPS: 541.23
14:43:06.674 [INFO] (trainer.py:105) Total Epi:   304 Steps:   10830 Episode Steps:   200 Return:  200.0000 FPS: 539.06
14:43:07.065 [INFO] (trainer.py:105) Total Epi:   305 Steps:   11030 Episode Steps:   200 Return:  200.0000 FPS: 511.40
14:43:07.425 [INFO] (trainer.py:105) Total Epi:   306 Steps:   11230 Episode Steps:   200 Return:  200.0000 FPS: 556.13
14:43:07.799 [INFO] (trainer.py:105) Total Epi:   307 Steps:   11430 Episode Steps:   200 Return:  200.0000 FPS: 536.09
14:43:08.163 [INFO] (trainer.py:105) Total Epi:   308 Steps:   11630 Episode Steps:   200 Return:  200.0000 FPS: 548.93
14:43:08.533 [INFO] (trainer.py:105) Total Epi:   309 Steps:   11830 Episode Steps:   200 Return:  200.0000 FPS: 541.06
```

Could you retry with latest version? If you have installed via `pip`, please uninstall it and install with developer version (to execute on the same version with mine).

```bash
$ cd /path/to/tf2rl
$ pip uninstall -y tf2rl
$ pip install -e .
```

**Comment by lichongcoco** [comment]
My reinstallation attempt was still wrong. The version I use is tf2rl 0.1.9, tensorflow 2.0.1.
My complete code:(I'm trying to find all the commands and understand the meaning of these parameters)

```
import gym

from tf2rl.algos.dqn import DQN
from tf2rl.experiments.trainer import Trainer

if __name__ == '__main__':
    
    parser = Trainer.get_argument()

    parser.set_defaults(max_steps=int(1000000)) 
    parser.set_defaults(episode_max_steps=int(1000)) 
    parser.set_defaults(n_experiments=1) 
    parser.set_defaults(show_progress=False) 
    parser.set_defaults(gpu=0) 
    parser.set_defaults(save_model_interval=int(1000)) 
    parser.set_defaults(save_summary_interval=int(1000)) 
    parser.set_defaults(model_dir=None)
    parser.set_defaults(dir_suffix='')

    # test settings
    parser.set_defaults(evaluate=False) 
    parser.set_defaults(test_interval=int(10000)) 
    parser.set_defaults(show_test_progress=False) 
    parser.set_defaults(test_episodes=5)
    parser.set_defaults(save_test_path=False) 
    parser.set_defaults(show_test_images=False)
    parser.set_defaults(save_test_movie=False)

     # replay buffer 
    parser.set_defaults(use_prioritized_rb=True) 
    parser.set_defaults(use_nstep_rb=True) 
    parser.set_defaults(n_step=4) 

   # others
    parser.set_defaults(logging_level='INFO') 

    parser = DQN.get_argument(parser)

    # Policy 
    parser.set_defaults(n_warmup=int(1000)) 
    parser.set_defaults(batch_size=32) 

    # OffPolicyAgent 
    parser.set_defaults(memory_capacity=int(1000000)) 

    # DQN 
    parser.set_defaults(enable_double_dqn=True) 
    # parser.set_defaults(enable_dueling_dqn=True) 
    parser.set_defaults(enable_categorical_dqn=True) 
    # parser.set_defaults(enable_noisy_dqn=True) 

    args = parser.parse_args()

    env = gym.make("CartPole-v0")
    test_env = gym.make("CartPole-v0")
    policy = DQN(
        enable_double_dqn=args.enable_double_dqn,
        enable_dueling_dqn=args.enable_dueling_dqn,
        enable_noisy_dqn=args.enable_noisy_dqn,
        enable_categorical_dqn=args.enable_categorical_dqn,
        state_shape=env.observation_space.shape,
        action_dim=env.action_space.n,
        target_replace_interval=300,
        units=[64, 64],
        discount=0.99,
        gpu=args.gpu,
        memory_capacity=args.memory_capacity,
        batch_size=args.batch_size,
        n_warmup=args.n_warmup)
    trainer = Trainer(policy, env, args, test_env=test_env)
    trainer()
```

Full error message:

```
07:25:12.577 [INFO] (trainer.py:99) Total Epi:    45 Steps:     939 Episode Steps:    23 Return:  23.0000 FPS: 1125.95
07:25:12.596 [INFO] (trainer.py:99) Total Epi:    46 Steps:     960 Episode Steps:    21 Return:  21.0000 FPS: 1166.56
07:25:12.612 [INFO] (trainer.py:99) Total Epi:    47 Steps:     976 Episode Steps:    16 Return:  16.0000 FPS: 1086.77
2020-02-19 07:25:18.475536: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2017.3.3\helpers\pydev\pydevd.py", line 1668, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm 2017.3.3\helpers\pydev\pydevd.py", line 1662, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2017.3.3\helpers\pydev\pydevd.py", line 1072, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2017.3.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/workspace/alice3.6/DQN.py", line 78, in <module>
    trainer()
  File "C:\workspace\alice3.6\venv\lib\site-packages\tf2rl\experiments\trainer.py", line 120, in __call__
    samples["rew"], np.array(samples["done"], dtype=np.float32))
  File "C:\workspace\alice3.6\venv\lib\site-packages\tf2rl\algos\dqn.py", line 244, in compute_td_error
    return self._compute_td_error_body(states, actions, next_states, rewards, dones)
  File "C:\workspace\alice3.6\venv\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "C:\workspace\alice3.6\venv\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 503, in _call
    self._initialize(args, kwds, add_initializers_to=initializer_map)
  File "C:\workspace\alice3.6\venv\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 408, in _initialize
    *args, **kwds))
  File "C:\workspace\alice3.6\venv\lib\site-packages\tensorflow_core\python\eager\function.py", line 1848, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "C:\workspace\alice3.6\venv\lib\site-packages\tensorflow_core\python\eager\function.py", line 2150, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\workspace\alice3.6\venv\lib\site-packages\tensorflow_core\python\eager\function.py", line 2041, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "C:\workspace\alice3.6\venv\lib\site-packages\tensorflow_core\python\framework\func_graph.py", line 915, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\workspace\alice3.6\venv\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 358, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "C:\workspace\alice3.6\venv\lib\site-packages\tensorflow_core\python\eager\function.py", line 2658, in bound_method_wrapper
    return wrapped_fn(*args, **kwargs)
  File "C:\workspace\alice3.6\venv\lib\site-packages\tensorflow_core\python\framework\func_graph.py", line 905, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in converted code:
    relative to C:\workspace\alice3.6\venv\lib\site-packages:

    tf2rl\algos\dqn.py:263 _compute_td_error_body  *
        indices = tf.concat(
    tensorflow_core\python\util\dispatch.py:180 wrapper
        return target(*args, **kwargs)
    tensorflow_core\python\ops\array_ops.py:1431 concat
        return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
    tensorflow_core\python\ops\gen_array_ops.py:1257 concat_v2
        "ConcatV2", values=values, axis=axis, name=name)
    tensorflow_core\python\framework\op_def_library.py:793 _apply_op_helper
        op_def=op_def)
    tensorflow_core\python\framework\func_graph.py:548 create_op
        compute_device)
    tensorflow_core\python\framework\ops.py:3429 _create_op_internal
        op_def=op_def)
    tensorflow_core\python\framework\ops.py:1773 __init__
        control_input_ops)
    tensorflow_core\python\framework\ops.py:1613 _create_c_op
        raise ValueError(str(e))

    ValueError: Shape must be rank 2 but is rank 3 for 'concat_1' (op: 'ConcatV2') with input shapes: [32,1], [32,1,51], [].
```

**Comment by keiohta** [comment]
Thank you for providing details. I reproduced the bug, and seems it is related to combination of double DQN and categorical DQN. I'll fix this soon.
In the mean time, please just refrain from using double DQN. You might be already aware of this but double DQN does not actually contribute performance as reported in Rainbow paper.
https://arxiv.org/pdf/1710.02298.pdf

**Comment by lichongcoco** [comment]
Thank you very much, tf2rl is very good. I used to code reinforcement learning myself, but I was always worried about the code I wrote. Now I can focus on the Env

**Comment by keiohta** [comment]
I'm really glad to hear that! Please don't hesitate to open issues. That helps quality of repo.

[This commit](https://github.com/keiohta/tf2rl/commit/f71cf8636e67d7bda6781fbe63834630931a2185) should have solved the problem. Please try with the latest master, or download the latest version via PyPI

**Comment by lichongcoco** [comment]
I upgraded to the latest version 0.1.11, but the problem persists ...
```
ValueError: in converted code:
    relative to C:\workspace\alice3.6\venv\lib\site-packages:

    tf2rl\algos\dqn.py:263 _compute_td_error_body  *
        indices = tf.concat(
    tensorflow_core\python\util\dispatch.py:180 wrapper
        return target(*args, **kwargs)
    tensorflow_core\python\ops\array_ops.py:1431 concat
        return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
    tensorflow_core\python\ops\gen_array_ops.py:1257 concat_v2
        "ConcatV2", values=values, axis=axis, name=name)
    tensorflow_core\python\framework\op_def_library.py:793 _apply_op_helper
        op_def=op_def)
    tensorflow_core\python\framework\func_graph.py:548 create_op
        compute_device)
    tensorflow_core\python\framework\ops.py:3429 _create_op_internal
        op_def=op_def)
    tensorflow_core\python\framework\ops.py:1773 __init__
        control_input_ops)
    tensorflow_core\python\framework\ops.py:1613 _create_c_op
        raise ValueError(str(e))

    ValueError: Shape must be rank 2 but is rank 3 for 'concat_1' (op: 'ConcatV2') with input shapes: [32,1], [32,1,51], [].
```

I found that setting this way will produce errors:
```
    parser.set_defaults(enable_double_dqn=True)
    parser.set_defaults(enable_categorical_dqn=True)
    parser.set_defaults(use_prioritized_rb=True)
```

this setting no problem:
```
parser.set_defaults(use_prioritized_rb=False)
```

**Comment by keiohta** [comment]
Is that really the latest version? The line 263 should be blank line.
https://github.com/keiohta/tf2rl/blob/master/tf2rl/algos/dqn.py#L263

If it does, could you give me the full information of your scripts to reproduce the bug?

**Comment by lichongcoco** [comment]
Since the latest version on pip is 0.1.9, I am installed with setup.py, the post-installation version number is 0.1.11, you mentioned that 263 lines are empty lines, I specifically opened the code to look at, and gethub code is not consistent, do not know what went wrong, I directly cover the code into" site-packages\tf2rl" and then run, no problem, thank you very much
