### ISSUE TITLE
TD3 examples change game error

### ISSUE THREAD

**Issue by lichongcoco** [keiohta/tf2rl#80]
I changed the game of TD3 examples,code like this:

```
import gym

from tf2rl.algos.td3 import TD3
from tf2rl.experiments.trainer import Trainer

if __name__ == '__main__':
    parser = Trainer.get_argument()
    parser = TD3.get_argument(parser)

    args = parser.parse_args()

    env = gym.make("CartPole-v0")
    test_env = gym.make("CartPole-v0")

    policy = TD3(
        state_shape=env.observation_space.shape,
        action_dim=env.action_space.n,
        gpu=args.gpu,
        memory_capacity=args.memory_capacity,
        batch_size=args.batch_size,
        n_warmup=args.n_warmup)
    trainer = Trainer(policy, env, args, test_env=test_env)
    trainer()
```

But running error:

```
08:27:37.533 [INFO] (trainer.py:99) Total Epi:   465 Steps:    9951 Episode Steps:    18 Return:  18.0000 FPS: 16997.01
08:27:37.535 [INFO] (trainer.py:99) Total Epi:   466 Steps:    9967 Episode Steps:    16 Return:  16.0000 FPS: 16463.40
08:27:37.537 [INFO] (trainer.py:99) Total Epi:   467 Steps:    9992 Episode Steps:    25 Return:  25.0000 FPS: 16283.76
Traceback (most recent call last):
  File "C:/workspace/alice3.6/td3.py", line 32, in <module>
    trainer()
  File "C:\workspace\alice3.6\venv\lib\site-packages\tf2rl\experiments\trainer.py", line 116, in __call__
    None if not self._use_prioritized_rb else samples["weights"])
  File "C:\workspace\alice3.6\venv\lib\site-packages\tf2rl\algos\ddpg.py", line 119, in train
    states, actions, next_states, rewards, done, weights)
  File "C:\workspace\alice3.6\venv\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "C:\workspace\alice3.6\venv\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 503, in _call
    self._initialize(args, kwds, add_initializers_to=initializer_map)
  File "C:\workspace\alice3.6\venv\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 408, in _initialize
    *args, **kwds))
  File "C:\workspace\alice3.6\venv\lib\site-packages\tensorflow_core\python\eager\function.py", line 1848, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "C:\workspace\alice3.6\venv\lib\site-packages\tensorflow_core\python\eager\function.py", line 2150, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\workspace\alice3.6\venv\lib\site-packages\tensorflow_core\python\eager\function.py", line 2041, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "C:\workspace\alice3.6\venv\lib\site-packages\tensorflow_core\python\framework\func_graph.py", line 915, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\workspace\alice3.6\venv\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 358, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "C:\workspace\alice3.6\venv\lib\site-packages\tensorflow_core\python\eager\function.py", line 2658, in bound_method_wrapper
    return wrapped_fn(*args, **kwargs)
  File "C:\workspace\alice3.6\venv\lib\site-packages\tensorflow_core\python\framework\func_graph.py", line 905, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in converted code:
    relative to C:\workspace\alice3.6\venv\lib\site-packages:

    tf2rl\algos\td3.py:78 _train_body  *
        td_error1, td_error2 = self._compute_td_error_body(
    tensorflow_core\python\eager\def_function.py:457 __call__
        result = self._call(*args, **kwds)
    tf2rl\algos\td3.py:132 _compute_td_error_body  *
        current_Q1, current_Q2 = self.critic([states, actions])
    tensorflow_core\python\keras\engine\base_layer.py:847 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    tf2rl\algos\td3.py:33 call  *
        x1 = tf.nn.relu(self.l1(xu))
    tensorflow_core\python\keras\engine\base_layer.py:812 __call__
        self.name)
    tensorflow_core\python\keras\engine\input_spec.py:213 assert_input_compatibility
        ' but received input with shape ' + str(shape))

    ValueError: Input 0 of layer L1 is incompatible with the layer: expected axis -1 of input shape to have value 6 but received input with shape [32, 5]
```
What parameters do I need to set for normal operation?

**Comment by keiohta** [comment]
This is just because TD3 does not support discrete output.
You can check what algorithms support discrete/continuous action in README.

**Comment by lichongcoco** [comment]
Thank you very much for your answer
