### ISSUE TITLE
Unable to find any devices for spec /device:GPU:0 [Op:__inference__train_body_2028]

### ISSUE THREAD

**Issue by tanjhysj0** [keiohta/tf2rl#82]
ddpg code run:
07:44:34.818 [INFO] (trainer.py:105) Total Epi:    44 Steps:    8800 Episode Steps:   200 Return: -1098.1678 FPS: 6714.39
07:44:34.849 [INFO] (trainer.py:105) Total Epi:    45 Steps:    9000 Episode Steps:   200 Return: -1082.6376 FPS: 7052.35
07:44:34.896 [INFO] (trainer.py:105) Total Epi:    46 Steps:    9200 Episode Steps:   200 Return: -1451.9158 FPS: 4320.54
07:44:34.941 [INFO] (trainer.py:105) Total Epi:    47 Steps:    9400 Episode Steps:   200 Return: -1390.2553 FPS: 4567.13
07:44:34.987 [INFO] (trainer.py:105) Total Epi:    48 Steps:    9600 Episode Steps:   200 Return: -1171.9928 FPS: 4364.63
07:44:35.031 [INFO] (trainer.py:105) Total Epi:    49 Steps:    9800 Episode Steps:   200 Return: -1178.7816 FPS: 4601.59
07:44:35.074 [INFO] (trainer.py:105) Total Epi:    50 Steps:   10000 Episode Steps:   200 Return: -1347.0888 FPS: 4847.24
Traceback (most recent call last):
  File "/home/serlon/Documents/Code/V2-DDPG-LTC/demo.py", line 27, in <module>
    trainer()
  File "/home/serlon/anaconda3/envs/tf/lib/python3.6/site-packages/tf2rl/experiments/trainer.py", line 122, in __call__
    None if not self._use_prioritized_rb else samples["weights"])
  File "/home/serlon/anaconda3/envs/tf/lib/python3.6/site-packages/tf2rl/algos/ddpg.py", line 119, in train
    states, actions, next_states, rewards, done, weights)
  File "/home/serlon/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "/home/serlon/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 520, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/serlon/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1823, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/serlon/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1141, in _filtered_call
    self.captured_inputs)
  File "/home/serlon/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1224, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)
  File "/home/serlon/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 511, in call
    ctx=ctx)
  File "/home/serlon/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unable to find any devices for spec /device:GPU:0 [Op:__inference__train_body_2028]
how?I have installed driver
I had try cuda-10.0 cuda-10.1,cuda-10.2 ,it's same error

**Comment by keiohta** [comment]
Hi @tanjhysj0, thanks for the report.
Which TensorFlow version are you using?

**Comment by tanjhysj0** [comment]
> @ tanjhysj0，您好，感谢您的举报。
> 您正在使用哪个TensorFlow版本？

I had try 2.0 and 2.1 ,same problem

**Comment by keiohta** [comment]
Sorry for late reply.
Can you try to run with CPU (instead of GPUs) by specifying `--gpu -1` on command line? This clarifies whether the error comes from GPUs or not.

According to your error message, it seems you can try that with following command:
```bash
$ python /home/serlon/Documents/Code/V2-DDPG-LTC/demo.py --gpu -1
```

If you will still encounter some errors, then it would be helpful if you can provide the full codes of your `/home/serlon/Documents/Code/V2-DDPG-LTC/demo.py`.

**Comment by keiohta** [comment]
I close this issue. If you have encountered the same issue, then please open this again.
