### ISSUE TITLE
Cannot run: run_apex_ddpg.py

### ISSUE THREAD

**Issue by cubicgate** [keiohta/tf2rl#91]
I am using Windows 10. When I ran run_apex_ddpg.py, I got:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Miniconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Miniconda3\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'policy_fn' on <module '__mp_main__' from 'C:\\tf2rl-master\\examples\\run_apex_ddpg.py'>

**Comment by keiohta** [comment]
Hi @cubicgate , sorry for late reply. I just didn't notice this issue.

We have changed the ApeX codes so that it passes unittest on Windows machine through GitHub Actions, so it should successfully run now.
However, we haven't tested training an agent on real environments since we don't have local Windows machine.
So, could you test the same command and let me know the results?

Thanks!

**Comment by cubicgate** [comment]
Thanks @keiohta for your help! I will try it.
